models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()

class Todo(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	task = db.Column(db.String(80), unique = True)
	complete = db.Column(db.Boolean, default=False)
	date_created = db.Column(db.DateTime, default=datetime.now())
	date_modified = db.Column(db.DateTime, default=datetime.now())

app.py
from flask import Flask
from models import db
from views import view

# new instance of the Flask class
app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'
db.init_app(app)

app.register_blueprint(view)

if __name__=="__main__":
	with app.app_context():
		db.create_all()
	app.run(debug=True, port=8000)

views.py
from flask import Blueprint,render_template,request,redirect,url_for
from datetime import datetime
from models import db,Todo

view = Blueprint('view', __name__)

@view.route("/")
def home():
	todo_list = Todo.query.all()
	return render_template("index.html", todo_list=todo_list)

@view.route("/add", methods=['POST'])
def add():
	new_todo = Todo(task=request.form.get('task'))
	db.session.add(new_todo)
	db.session.commit()
	return redirect(url_for('view.home'))

@view.route("/update/<todo_id>")
def update(todo_id):
	todo = Todo.query.filter_by(id=todo_id).first()
	todo.complete = not todo.complete
	todo.date_modified = datetime.now()

	# print(f"{todo.date_created} --- {todo.date_created.timestamp()}")
	# print(f"{todo.date_modified} --- {todo.date_modified.timestamp()}")
	# if todo.date_modified > todo.date_created:
	# 	print("> True!")
	# else:
	# 	print("> False")

	db.session.commit()
	return redirect(url_for('view.home'))

@view.route("/delete/<todo_id>")
def delete(todo_id):
	todo = Todo.query.filter_by(id=todo_id).first()
	db.session.delete(todo)
	db.session.commit()
	return redirect(url_for('view.home'))

@view.route("/page2")
def page():
	return render_template('page2.html')

templates/base.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
	<nav>
		<div style="flex:1;">
			<a href="{{ url_for('view.home') }}">Home</a>
			<a href="{{ url_for('view.page') }}">Page2</a>
		</div>
	</nav>
	<div id="page_content">{% block content %}{% endblock %}</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
	<!-- FORM -->
	<div>
		<h1>To Do List</h1>
		<form action="/add" method="post">
			<div>
				<label>Todo task <input type="text" name="task" placeholder="Enter a Task"></label>
				<button type="submit">Add Task</button>
			</div>
		</form>
	</div>
	<!-- TASKS -->
	<div id="list-tasks">
	{% for todo in todo_list %}
		{% if todo.complete %}
		<div class="task checked">
			<div>
				<h3>{{ todo.id }} - {{ todo.task }}</h3>
				<a href="/update/{{todo.id}}">Mark as Uncomplete</a>
				<a class="del" href="/delete/{{todo.id}}">Delete Task</a>
			</div>
		{% else %}
		<div class="task">
			<div>
				<h3>{{ todo.id }} - {{ todo.task }}</h3>
				<a href="/update/{{todo.id}}">Mark as Complete</a>
				<a class="del" href="/delete/{{todo.id}}">Delete Task</a>
			</div>
		{% endif %}
			<div>
				{% if todo.date_modified > todo.date_created %}
				<div>Date Modified: {{ todo.date_modified.strftime('%d %b %y @ %H:%M:%S') }}</div>
				{% endif %}
				<div>Date Created: {{ todo.date_created.strftime('%d %b %y @ %H:%M:%S') }}</div>
			</div>
		</div>
	{% endfor %}
	</div>
{% endblock %}

templates/page2.html
{% extends 'base.html' %}
{% block content %}

<h2>Hey there</h2>

{% endblock %}